AWSTemplateFormatVersion: '2010-09-09'
Description: 'chocolate-lotto

  '
Globals:
  Function:
    Timeout: 20
Resources:
  GetTicketFunction:
    Properties:
      CodeUri: s3://poppulo-deployments-test/539de7b16e7f6d5476c955880dff947c
      Events:
        GetWinner:
          Properties:
            Method: get
            Path: /lotto/ticket
          Type: Api
      Handler: com.poppulo.chocolate.GetTicketHandler::handleRequest
      MemorySize: 256
      Policies:
      - Statement:
        - Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
          Effect: Allow
          Resource: '*'
        - Action:
          - dynamodb:PutItem
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - LottoTable
            - Arn
        Version: '2012-10-17'
      Runtime: java8
    Type: AWS::Serverless::Function
  GetWinnerFunction:
    Properties:
      CodeUri: s3://poppulo-deployments-test/539de7b16e7f6d5476c955880dff947c
      Events:
        GetWinner:
          Properties:
            Method: get
            Path: /lotto
          Type: Api
      Handler: com.poppulo.chocolate.GetWinnerHandler::handleRequest
      MemorySize: 256
      Policies:
      - Statement:
        - Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
          Effect: Allow
          Resource: '*'
        - Action:
          - dynamodb:Query
          Effect: Allow
          Resource:
          - Fn::GetAtt:
            - LottoTable
            - Arn
        Version: '2012-10-17'
      Runtime: java8
    Type: AWS::Serverless::Function
  LottoTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: game
        AttributeType: S
      - AttributeName: ticketValue
        AttributeType: N
      KeySchema:
      - AttributeName: game
        KeyType: HASH
      - AttributeName: ticketValue
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName: lotto
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
